name: OpenTofu Validate

on:
  pull_request:
    branches:
      - main
    paths:
      - 'infra/prod/**.tf'
      - 'infra/prod/**.tfvars'

permissions:
  contents: read
  id-token: write

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install OpenTofu
        uses: opentofu/setup-opentofu@9d84900f3238fab8cd84ce47d658d25dd008be2f # v1.0.8
        with:
          tofu_version: 1.11.5   # pin to the version you use locally

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_GITHUB_ACTIONS_ROLE_ARN }}
          aws-region: eu-central-1   # change to your region

      - name: Tofu version
        run: tofu version

      - name: Tofu init
        run: tofu init
        working-directory: ./infra/prod   # change to your tf root if different

      - name: Tofu format check
        run: tofu fmt -check
        working-directory: ./infra/prod

      - name: Tofu validate
        run: tofu validate
        working-directory: ./infra/prod

      - name: TF Lint install
        uses: terraform-linters/setup-tflint@90f302c255ef959cbfb4bd10581afecdb7ece3e6 # v4.1.1

      - name: tf linting
        run: |
          tflint --init
          tflint
        working-directory: ./infra/prod

      - name: Checkov
        uses: bridgecrewio/checkov-action@002cd2e8cc0fe0535e6f364509e091c1a9870efa # v12.3093.0
        with:
          directory: ./infra/prod
          soft_fail: true

      - name: Tofu plan
        run: tofu plan -out=tfplan
        working-directory: ./infra/prod

      - name: Upload plan to S3
        run: |
          aws s3 cp ./tfplan s3://jobassistant-prod-pipeline-artifacts/plans/tfplan-${{ github.sha }}
        working-directory: ./infra/prod

      - name: Save plan summary
        run: |
          tofu show -no-color tfplan 2>&1 | tee $GITHUB_STEP_SUMMARY
        working-directory: ./infra/prod